class UserNotFoundError(Exception):
    pass


class AvailabilityError(Exception):
    pass
